### ISSUE TITLE
Banned and Reconnecting crash

### ISSUE THREAD

**Issue by asdfxD** [Pisex/cs2-bans#1]
First, big thanks for this plugin.

banning works fine, but if you banned and try to reconnect, the server crashes. also my server crashes when i ban myself for testing and try to reconnect.. the server instantly crash.

@Windows

**Comment by mihaigsm2003** [comment]
yes, also ban not expire, i banned me for 1 minut, never can connect to server after, only after remove manual id3 from list and restart server!

**Comment by asdfxD** [comment]
plugin stopped working since last update, i did not changed anything and meta list now says "No plugins loaded."

Edit: Update Metamod to latest version and it loads.
Edit 2: Nope, server crashes on connect when this plugin is loaded.

**Comment by asdfxD** [comment]
Server is still crashing with 1.1 when i'm banned and try to reconnect.

**Comment by asdfxD** [comment]
still unsolved, but closed.

ok
