### ISSUE TITLE
Userid ban not working

### ISSUE THREAD

**Issue by MissXecutioner** [Pisex/cs2-bans#11]
![image](https://github.com/Pisex/cs2-bans/assets/73059032/7118f0a2-0c6d-47ef-a335-b12a1704f0ae)

**Comment by MissXecutioner** [comment]
![image](https://github.com/Pisex/cs2-bans/assets/73059032/7e046010-b48e-4dd4-ad8c-34b3a9437c69)

**Comment by Pisex** [comment]
Userid is the number of players relative to the slot on the server
