### ISSUE TITLE
Problem with admins permission and question about save bans. 

### ISSUE THREAD

**Issue by Zerov0v** [Pisex/cs2-bans#13]
I have problem with admins. If admin have Steamid starting with 0:0 or 0:1 or 1:0 console shows "You are denied acces" works only for 1:1. And question for bans.ini why file saves only account id not steamid and what mean second line of numbers in this file? 
![IMG_20231009_080206](https://github.com/Pisex/cs2-bans/assets/147235619/53bb62d8-f068-41e8-bcd0-912d0604847d)

**Comment by asdfxD** [comment]
All steam ids are STEAM_0:0: or STEAM_0:1, thats the old source steam id (css, tf2,..) in csgo/cs2 it is STEAM_1:X:

just replace the first 0 with 1 and all is working.

**Comment by asdfxD** [comment]
does not matter what steam id it is. important is, replace the first 0 with 1 (STEAM_0:0:XXXX -> STEAM_1:0:XXXX)

one of my steam id is STEAM_0:0:585XXXX

added to admins.ini STEAM_1:0:585XXXX

tested and working

**Comment by Zerov0v** [comment]
Ok i see my mistake but i can add only 12 admins if i add more than 12 rest of them above this number don't have permission

**Comment by Zerov0v** [comment]
What about marked numbers in screenshot what that means?
