### ISSUE TITLE
Admins access codes?

### ISSUE THREAD

**Issue by sminee** [Pisex/cs2-bans#14]
I added myself and a friend on admins.ini with the steamid and we still don't have access on server.
What codes should we put after steamid in order to have full access on commands?

**Comment by asdfxD** [comment]
You added wrong steam id.

**Comment by wizzardoff** [comment]
i also have that problem. I copied my and friends steam id from od admin_simple.ini and put it here,i dont have access. Also checked it in steam id finder and its 100% exact. Is it working with callsic id or does iot need id3 like original server cs2 console lists id3 when players connect. I always get:
[Client] [Admin] You are denied access

**Comment by Dilyar23** [comment]
+1 аналогичная проблема

**Comment by Pisex** [comment]
In order for stymaidi to be considered correct, you need to do the following

For example, we have this SteamID
STEAM_0:0:795292592

To make it correct you need to replace the beginning (STEAM_0) with STEAM_1 to make it like this
STEAM_1:0:795292592

**Comment by wizzardoff** [comment]
I already have STEAM_1,nothing changed

**Comment by Pisex** [comment]
Show me where your file and its contents are located

**Comment by wizzardoff** [comment]
/game/csgo/addons/configs/admin_base . Its default in release 1.2.1

**Comment by Pisex** [comment]
Give me a link to your stim account and the contents of the config

**Comment by wizzardoff** [comment]
i just reloaded all from scratch, release 1.2.1 and finally it started working somehow. Thanks for your replies and effort :)

**Comment by mayersgamer** [comment]
[Client] [Admin] You are denied access 

"Config"
{
	 "STEAM_0:1:68620657"		"1"
}

never mind i put 1 instead of 0 in my steam id and its working

**Comment by teamcity-topliner** [comment]
same problem
STEAM_ID already have 1 in it
Can't fix it

**Comment by tensX** [comment]
same problem
STEAM_ID already have 1 in it
But it doesn't work anyway and returns “access denied”

admins.ini

"Config"
{
"STEAM_1:0:33042879" "1"
}

**Comment by Dying-Ducks** [comment]
I have the same issue.

I have a Steam Account with the ID STEAM_0:0:XXXXXXXX
I changed it to STEAM_1:0:XXXXXXXX but that didnt helped.

Then I tried another Account with an ID STEAM_0:1:XXXXXXXX
I changed it to STEAM_1:1:XXXXXXXX but that didnt helped.

Whatever I set in the admins.ini I always get "access denied".
