### ISSUE TITLE
Problem with 3 digit user ID.

### ISSUE THREAD

**Issue by Zerov0v** [Pisex/cs2-bans#16]
I have a lot of people coming through the server and sometimes user id for example is 529. Console shows no valid user on that id when i try kick or ban that user.
![image](https://github.com/Pisex/cs2-bans/assets/147235619/ba4b955d-c24f-4c56-b573-471157fea469)
![image1](https://github.com/Pisex/cs2-bans/assets/147235619/8259bfa9-5ed7-49c0-a528-d5d5513da1dc)

**Comment by Pisex** [comment]
userid is a number not exceeding the number of slots and if you don’t know it, then just use nickname
