### ISSUE TITLE
[REQ] Support for adding admins via command

### ISSUE THREAD

**Issue by crashzk** [Pisex/cs2-bans#19]
Support for adding/removing admins via commands, something like:
- `!addadmin "STEAM_ID" "Admin Group/Flags" "Time"`
- `!removeadmin "STEAM_ID"`

Time would be interesting to add so that the admins are automatically removed after the time we set expires.

Support for adding admin would be cumulative, that is, if I add admin twice for the same player, the time will be accumulated, that is, the first time I add 120 seconds, the second time I add admin before the time expires, add another 80 and add them all the time and update to 200.

**Comment by Pisex** [comment]
Was added in this update
