### ISSUE TITLE
Crash server after add ban (linux)

### ISSUE THREAD

**Issue by dredek** [Pisex/cs2-bans#2]
When I used cmd in console **mm_ban <userid> <time in s>**  my server crashing.

> KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file addons/configs/admins.ini
Config, 

> terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi

My admins.ini config: https://pastebin.com/1L1T7sKR

**Comment by asdfxD** [comment]
i got the same in windows

**Comment by mihaigsm2003** [comment]
server crash when wrong ban comannd, or user not on server

**Comment by dredek** [comment]
It would be appropriate fix. If admin write wrong user it will crashed.
