### ISSUE TITLE
gag not working

### ISSUE THREAD

**Issue by exababy** [Pisex/cs2-bans#22]
When you peck someone, they can continue to talk on chat or when you peck them again, they create a new record on sql and do not update the old record.

**Comment by Pisex** [comment]
It works, it's just that other plugins may conflict, I'll release an update today

**Comment by Pisex** [comment]
I'm not deleting it so I can put past bans, mutes, gags somewhere on the web.

**Comment by exababy** [comment]
and gamedata.txt file as needed

When you slap someone, it doesn't do damage, after a while the server crashes

**Comment by Pisex** [comment]
I haven't observed this, but the damage is done, it's just that the information isn't applied immediately

**Comment by Pisex** [comment]
It's the visual

**Comment by exababy** [comment]
Okey, I will continue to report as I use it, I wish you success in your project development process.
