### ISSUE TITLE
version 2.1 !admin dont work

### ISSUE THREAD

**Issue by jinnixyz** [Pisex/cs2-bans#24]
I downloaded the new version 2.1 but when I enter !admin it tells me I don't have access to the command.
I have the admin.cfg from 2.0 and I am registered there as admin. There is no admin.cfg in 2.1 or do I no longer need it?

**Comment by Pisex** [comment]
(mm_)!add_admin <admin_name> <steamid64> <duration(minutes)/0 (permanent)> <flags> <immunity> <optional comment>
Use this to add yourself as an admin

**Comment by jinnixyz** [comment]
i cant use !add_admin or mm_ its say i have still no access to this command. I can't run command because I'm not an admin

**Comment by Pisex** [comment]
No one forbids you to write this command using the server console
