### ISSUE TITLE
 No more rights after changing the map

### ISSUE THREAD

**Issue by jinnixyz** [Pisex/cs2-bans#26]
When I restart the server and the startmap comes up, it recognizes me as admin. 
When the map is changed and I enter !admin I get this error message [ADMIN]You don't have access to this command.

**Comment by Pisex** [comment]
What is your sv_hibernate_when_empty value?

**Comment by jinnixyz** [comment]
false, 0

**Comment by Pisex** [comment]
What plugins are you running?

**Comment by jinnixyz** [comment]
sorry for late answer !
![1](https://github.com/Pisex/cs2-bans/assets/89946984/61dcbda2-8d34-4c9a-a1d4-c7f83e145759)

And of cours in meta list : 
[Client]   [01] AdminSystem (2.1.1) by Pisex
[Client]   [02] CounterStrikeSharp (0.1.0) by Roflmuffin
[Client]   [03] MysqlMM (1.0.0.0) by Poggu

**Comment by jinnixyz** [comment]
> What is your sv_hibernate_when_empty value?

i have in Gamemode.cfg and server.cfg sv_hibernate_when_empty 0, but when I change the map, it automatically goes back to 1
