### ISSUE TITLE
Sugestion new command

### ISSUE THREAD

**Issue by dredek** [Pisex/cs2-bans#5]
Add new cmd: mm_lastban
Possibility of giving a ban for people who disconnect from server.

**Comment by Pisex** [comment]
I think it makes sense, but only if you add in mm_ban to ban by steamid, and using the command mm_lasts to make the output of the last 10 players who left the server by type 
1. Flax(12352332)
2. Sgk(12332533)
...
But so far I do not see the need

**Comment by asdfxD** [comment]
@Pisex possible to add banned player names automatically in bans.ini?

"Config"
{
	"10774537"	"NamePlayer1"     "0"
}

**Comment by Pisex** [comment]
No

**Comment by mihaigsm2003** [comment]
if is posible pls add reset score, but i think in this mode is posible only by admins

**Comment by asdfxD** [comment]
> if is posible pls add reset score, but i think in this mode is posible only by admins

+1
