### ISSUE TITLE
My steamid does not work

### ISSUE THREAD

**Issue by Abdelakil** [Pisex/cs2-bans#7]
Hello, thanks for this great plugin.
I want to point to an issue I am facing, actually my steamid does not give me an admin acces, but it does for some other admins, I guess it has something to do with steam id lenght ?
Here is my steamid:
STEAM_0:0:7891XXX (XXX for privacy)
Cheers,

**Comment by asdfxD** [comment]
STEAM_**1**:0:7891XXX

**Comment by Abdelakil** [comment]
Thanks @asdfxD, it worked.
