### ISSUE TITLE
Symbolic file gameinfo.gi

### ISSUE THREAD

**Issue by crashzk** [Pisex/cs2-bans#8]
My CS2 server is rented from a host, and the `gameinfo.gi` file would be a symbolic file, I cannot change it.

Any ways to get around this? Or just contact my host to check this?

![image](https://github.com/Pisex/cs2-bans/assets/32937653/0c069014-eb26-40e5-b351-a14bf7d43e25)

**Comment by Pisex** [comment]
You should write and ask to make a file without using links

**Comment by crashzk** [comment]
Another thing, I saw that when I try to edit the `gameinfo.gi` file it asks to edit the `gameinfo.gi` file but in the `csgo_core` folder, would there be any difference in editing the one it recommends? Or just testing to find out?

**Comment by Pisex** [comment]
I haven't tried it, but you can drink it yourself

**Comment by crashzk** [comment]
Just a feedback, just editing the `gameinfo.gi` file from the `csgo` folder works.
